### ISSUE TITLE
The command indicated in the documentation doesn't appear

### ISSUE THREAD

**Issue by codeDude64** [krivahtoo/silicon.nvim#13]
I've installed the plugin like the documentation indicated, even though I installed it in the console with the command `./install.sh build` in the correct directory.
I copied and pasted the setup that the doc mentioned, but the command `'<,'>Silicon` doesn't appear. I can do nothing with the plugin.

I know that the plugin is installed because I can print `require 'silicon'` appearing in a table with 2 function setup and capture.

**Comment by krivahtoo** [comment]
The `Silicon` command is created within the `setup` it should available after invoking the `setup()` function.

Which nvim version are you using?

**Comment by codeDude64** [comment]
I apologize, I figured out that I never require the file where the setup is expected.
