### ISSUE TITLE
Crashes For Custom Themes

### ISSUE THREAD

**Issue by WilliamWelsh** [krivahtoo/silicon.nvim#14]
I have a `base16-tomorrow.dark.thTheme` file set up for both `bat` and `silicon`, they are both set to use that theme as a default, and both work fine from the command-liine, but when I use `base16-tomorrow.dark` as the `theme` option in this plugin, it crashes.
```bash
thread '<unnamed>' panicked at 'no entry found for key', src/lib.rs:192:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: Rust panics must be rethrown
fish: Job 1, 'nvim $argv' terminated by signal SIGABRT (Abort)
```

**Comment by krivahtoo** [comment]
fixed via 3f9f5c4
