### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Sanix-Darker** [krivahtoo/silicon.nvim#18]
Am getting an error when i try to create a silicon image !
Please see in the below test gif : 
![Peek 2022-12-18 12-14](https://user-images.githubusercontent.com/22576758/208295208-26bfc517-d218-4201-8b73-682de4afcc87.gif)

**Comment by krivahtoo** [comment]
which neovim version are you using?

**Comment by Sanix-Darker** [comment]
> which neovim version are you using?
the nightly !

But as i can see it's fixed !
Thanks for the fix !
