### ISSUE TITLE
:PlugInstall / :PlugUpdate failure: "invalid reference: master"

### ISSUE THREAD

**Issue by winder** [krivahtoo/silicon.nvim#2]
Silicon fails to install with an error:

`fatal: invalid reference: master`

I don't use a lot of plugins, and have not customized neovim much, so it's entirely possible that my installation has too much deprecated cruft and legacy things from classic vim that somehow broke things.

My dotfiles are checked into a git repo, and symlinks into that repo are managed with stow. I wonder if my `master` branch could somehow collide with the silicon.nvim `main` branch?

Here is my attempt to install: https://github.com/winder/dotfiles/commit/237af1c4c10bd83008c16e8ee55c2ae124b65123
After which `:PlugInstall` reports the above error.

**Comment by krivahtoo** [comment]
This might help: [glepnir/zephyr-nvim#3#issuecomment-100833429](https://github.com/glepnir/zephyr-nvim/issues/3#issuecomment-100833429)

**Comment by winder** [comment]
Thanks, I was able to get the install to work without error using that thread.

However, now that it's installed `:'<,'>Silicon [file]` isn't working. It says `E492: Not an editor command: :'<,'>Silicon`.

I guess that's because I haven't put the require command in my init file. Usage instructions for someone using a .vim config file would be helpful :)

Closing because the topic of this issue has been resolved.

**Comment by krivahtoo** [comment]
> However, now that it's installed `:'<,'>Silicon [file]` isn't working. It says E492: Not an editor command: `:'<,'>Silicon`.

It works when on visual mode.

`'<,'>` actually means range like `12,20`. in this case `'<` means start of visual selection and `'>` the end.

**Comment by winder** [comment]
I selected the text in visual mode, use `:` to get into visual command mode and type `Silicon`

**Comment by krivahtoo** [comment]
Did you initialize the plugin with `require('silicon').setup(...)` ?
