### ISSUE TITLE
Wayland support using 'wlr-copy' instead of xclip?

### ISSUE THREAD

**Issue by matthis-k** [krivahtoo/silicon.nvim#21]
Currently not usable with Wayland clipboard

**Comment by treatybreaker** [comment]
So this is my _ghetto_ quick implementation during a work call for wl-clipboard:

```rust
#[cfg(target_os = "linux")]
pub fn dump_image_to_clipboard(image: &DynamicImage) -> anyhow::Result<()> {
    use std::{process::Stdio, io::Write};

    let mut temp = tempfile::NamedTempFile::new()?;
    println!("{}", temp.path().to_str().unwrap());
    image.write_to(&mut temp, ImageOutputFormat::Png)?;
    let mut cmd = Command::new("wl-copy")
        .args([
            "-t",
            "image/png",
        ])
        .stdin(Stdio::piped())
        .spawn()
        .map_err(|e| format_err!("Failed to copy image to clipboard: {}", e))?;

    // NOTE: We get to do all this reading and writing from the files because wl-copy only accepts
    // files on STDIN
    let mut stdin = cmd.stdin.take().expect("Failed to open stdin");
    let temp_file_path = temp.path().to_str().unwrap();
    let file_content = std::fs::read(temp_file_path).expect(&format!("Unable to open {}!", temp_file_path));
    stdin.write_all(&file_content[..]).expect("Unable to write stdin!");
    Ok(())
}
```

I've replaced the original function that had x-clip. This works for me just fine, but I've, as a side effect, nuked xclip support. Not ideal.

**Comment by krivahtoo** [comment]
Nice.
I was planning to add `wl-copy` as a fallback if `xclip` fails or vise versa.

**Comment by treatybreaker** [comment]
I'm going to get a PR to you hopefully this evening from [my branch here](https://github.com/treatybreaker/silicon.nvim/tree/feat/wl-clip-support). What I think the best way to do this is attempt to call both `xclip` & `wl-copy` and if one succeeds then don't boil an error up.

If both fail then send the error up the stack.

This avoids the situation on some Wayland systems in which `xclip` & `wl-copy` are both installed and only one is called by us, potentially not populating their clipboard correctly.

**Comment by krivahtoo** [comment]
That would be awesome. 👍🏾

**Comment by treatybreaker** [comment]
Seems to work:

![image](https://user-images.githubusercontent.com/58627896/220756961-62421057-9621-4b25-99a9-49766ef67fbf.png)

Can someone validate against [my branch](https://github.com/treatybreaker/silicon.nvim/tree/feat/wl-clip-support) for xclip?

**Comment by treatybreaker** [comment]
I've uninstalled both `wl-clipboard` & `xclip` and it would appear the errors are working as anticipated.

With only one or the other installed the image is getting copied to my clipboard. The branch appears to work just fine for me, but additional verification would be good. I'll open a PR and verification can happen there.
