### ISSUE TITLE
Address boundary error

### ISSUE THREAD

**Issue by marcioflaviof** [krivahtoo/silicon.nvim#33]
I'm trying to use this app with lazy.nvim in nvim 0.8 and getting Address boundary error, it's possible to make it work in 0.8 or it's not supported? Or I'm doing something wrong?

my configs:
```lua
	{
		"krivahtoo/silicon.nvim",
		build = "./install.sh",
		config = function()
			require("silicon").setup({
				font = "JetBrains Mono NL=16",
				theme = "Dracula",
				output = {
					path = "home/mf/Pictures/Screenshots",
				},
			})
		end,
	},
```
![image](https://user-images.githubusercontent.com/44372758/223742147-96da1a38-1b61-47d0-819b-070613596b9d.png)

**Comment by krivahtoo** [comment]
> ..it's possible to make it work in 0.8 or it's not supported?

Yeah, `0.8` is supported.

I cannot reproduce this. Which OS are you using? And does this happen when opening nvim or when running the `Silicon` command?

**Comment by marcioflaviof** [comment]
I'm using manjaro, this happen when running the Silicon command.
![image](https://user-images.githubusercontent.com/44372758/223762976-3796fbe7-e287-4259-970c-77908562a21c.png)

**Comment by krivahtoo** [comment]
Have you tried building from source?

with:
```lua
{
  "krivahtoo/silicon.nvim",
  build = "./install.sh build",
  ...
}
```

**Comment by marcioflaviof** [comment]
Build from source worked! Thanks.
