### ISSUE TITLE
Still getting error trying to install on arm64

### ISSUE THREAD

**Issue by zeitchef** [krivahtoo/silicon.nvim#7]
I was happy to see the MR regarding support for arm64, but I'm still having an issue on install:

<img width="723" alt="Screen Shot 2022-10-18 at 22 45 03" src="https://user-images.githubusercontent.com/6670659/196541286-9103e8f8-ad64-4b44-a5b0-b7b8ef425ade.png">

Any idea what might be happening here?

**Comment by krivahtoo** [comment]
Sorry i don't have a mac to test this on.
Have tried downloading manually from [silicon.nvim/releases](https://github.com/krivahtoo/silicon.nvim/releases/tag/v0.2.1) and extracting to `~/.local/.../silicon.nvim`?

**Comment by augustocdias** [comment]
The problem is that in your CI you're not passing the target in the cargo build step. You're just installing the target in the machine. Since the host is probably x86, it will default to the host's arch. So you're essentially publishing a x86 build twice.

**Comment by krivahtoo** [comment]
Right. Thanks @augustocdias 
a61f245 should fix.

**Comment by augustocdias** [comment]
Now it works :)
