### ISSUE TITLE
default watermark text at the end of a snap ?

### ISSUE THREAD

**Issue by Sanix-Darker** [krivahtoo/silicon.nvim#9]
i really love this plugin and as a blogger, i need sometimes to add a watermark on my snaps, and i was thinking, what if it's possible to set a default watermark text at the corner of the image ? like this (the @ sanixdarker at the bottom right ): 

![img](https://res.cloudinary.com/practicaldev/image/fetch/s--w0Pwv_1I--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/gh260avy87m5rzw4yhrh.png)

WDYT ? 🤔

**Comment by krivahtoo** [comment]
Yeah, that's a good idea. I will try implementing this.

I'm not sure why it is not implemented in silicon and [watermark option is commented out](https://github.com/Aloxaf/silicon/blob/master/src/bin/silicon/config.rs#L203).
